Adapters manager implementation
CESNET/perun.connector pull request #13
Opened 2022-03-28 09:27 UTC by PeterBolha

2022-04-14 08:33 UTC, xpavlic requested changes

2022-04-14 08:33 UTC, xpavlic commented on adapters/AdaptersManager.py
> +                if 'NotExistsException"' in ex.body:
```suggestion
                if 'notexistsexception"' in ex.body.lower():
```

2022-04-14 08:34 UTC, xpavlic commented
Also please rebase branche to resolve conflict and drop [Integrated correct adapters interface](https://github.com/CESNET/proxyaai_perun_connection_manager/pull/13/commits/95ba23f4dd4c70d104c3af46b2201c2f31830162)

2022-04-14 09:02 UTC, PeterBolha commented on adapters/AdaptersManager.py
> +                )
Okay so in this case it means I should remove the ConfigStore.get_xxx_config() and extract the information from the `adapter_info` instead?

2022-04-14 09:06 UTC, xpavlic commented on adapters/AdaptersManager.py
> +                )
Exactly.

2022-04-21 22:53 UTC, xpavlic requested changes

2022-04-21 22:53 UTC, xpavlic commented on adapters/AdaptersManager.py
> +    def get_vo(self, short_name=None, id=None) -> VO:
I would add type (shor_name: str,  id: int)

2022-04-25 11:54 UTC, xpavlic requested changes

2022-04-25 11:54 UTC, xpavlic commented on adapters/AdaptersManager.py
> +    def __init__(self):
Pass config as parameter

2022-04-25 11:54 UTC, xpavlic commented on adapters/AdaptersManager.py
> +        self._ADAPTERS = {}
Remove underscore, we need to access it in tests.

2022-04-26 06:14 UTC, PeterBolha commented on adapters/AdaptersManager.py
> +    def __init__(self):
```
def __init__(self, config=ConfigStore.get_adapters_manager_config()):
    self._logger = Logger.get_logger(self.__class__.__name__)
    self._STARTING_PRIORITY = 1
    self.adapters = {}

    adapters_info = config["adapters"]
```

2022-04-26 14:27 UTC, xpavlic commented on adapters/AdaptersManager.py
> +    def __init__(self):
exactly

2022-04-27 18:22 UTC, xpavlic requested changes
Squash commits, then we will merge this.

2022-04-27 18:22 UTC, xpavlic commented on adapters/AdaptersManager.py
> +    def execute_method_by_priority(self, method_name: str, *args):
add _ to method name

2022-04-27 18:22 UTC, xpavlic commented on adapters/AdaptersManager.py
> +    def get_caller_name(self):
same as above

2022-04-28 07:22 UTC, merged

2022-05-16 11:43 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-16 12:13 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: